spring:
  application:
    name: bapp-home
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        order_updates: true
        jdbc:
          batch_size: 500
        generate_statistics: false
        cache:
          use_query_cache: false
          use_second_level_cache: false
    #    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:bapp_home}
    username: ${DB_USER:root}
    password: ${DB_PWD:}
    hikari:
      pool-name: HomeSpringJPAHikariCP
      maximum-pool-size: 10
      max-lifetime: 60000 # 1 minute wait time
      auto-commit: false
      data-source-properties:
        reWriteBatchedInserts: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE